[package]
name = "rdiff"
version = "0.0.1"
authors = ["Caleb Kornegay <caleb.kornegay@gmail.com>"]
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
similar = "2.2"
tui-input = "0.11.1"
clap = { version = "4.5.37", features = ["derive"] }
sha2 = "0.10.8"
